version: '3.4'

services:
  csml-engine:
    image: clevy/csml-engine
    container_name: csml-engine
    command: "npm start"
    restart: always
    ports:
      - 3000:3000
    links:
      - csml-mongo
    depends_on:
      - csml-mongo
    env_file:
      - .env
    environment:
      MONGODB_HOST: csml-mongo
      MONGODB_PORT: 27017

  csml-mongo:
    image: mongo
    container_name: csml-mongo
    restart: always
    ports:
      - '27017-27019:27017-27019'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: csml
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data:/data/db

volumes:
  mongo_data:
