name: Create Docker Image

on:
  release:
    types: [created, edited]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get RELEASE_VERSION
      run: |
        echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
        echo "preparing release version $RELEASE_VERSION"

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Docker login
      run: echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login --username csmlengineci --password-stdin

    - name: Build the image
      run: |
        docker build . --file Dockerfile --tag clevy/csml-engine

    - name: Publish the image
      run: |
        docker tag clevy/csml-engine clevy/csml-engine:$RELEASE_VERSION
        docker push clevy/csml-engine
        docker push clevy/csml-engine:$RELEASE_VERSION
