name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Docker login
      run: echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login --username csmlengineci --password-stdin

    - name: Build the image
      run: |
        docker build . --file Dockerfile --tag clevy/csml-engine

    - name: Publish the image
      run: |
        docker push clevy/csml-engine

    - name: Create a Release
      uses: actions/create-release@v1
